[package]
name = "projetrust"
version = "0.1.0"
authors = ["Gokhan & Ala eddine"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
printpdf = "0.3.2"

[dependencies.gtk]
version = "0.9.0"
features = ["v3_16"]
